//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkySouls3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkySouls3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 0f 11 44 24 20       movss  DWORD PTR [rsp+0x20],xmm0
        ///50                      push   rax
        ///66 0f 7e d8             movd   eax,xmm3
        ///3d 00 40 9c 46          cmp    eax,0x469c4000
        ///74 1b                   je     2d &lt;skipCall&gt;
        ///3d 00 42 9c 46          cmp    eax,0x469c4200
        ///74 14                   je     2d &lt;skipCall&gt;
        ///3d 00 44 9c 46          cmp    eax,0x469c4400
        ///74 0d                   je     2d &lt;skipCall&gt;
        ///3d 00 48 9c 46          cmp    eax,0x469c4800
        ///74 06                   je     2d &lt;skipCall&gt;
        ///58    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CinderPhaseLock {
            get {
                return ResourceManager.GetString("CinderPhaseLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # 7 &lt;_main+0x7&gt;
        ///48 8b 80 90 1f 00 00    mov    rax,QWORD PTR [rax+0x1f90]
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string SaveTargetPtr {
            get {
                return ResourceManager.GetString("SaveTargetPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 89 c1                mov    rcx,rax
        ///ba 01 00 00 00          mov    edx,0x1
        ///48 be 00 00 00 00 00    movabs rsi,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d6                   call   rsi
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string WarpCall {
            get {
                return ResourceManager.GetString("WarpCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cemetery of Ash,0x5A03,6,4001951,,
        ///Iudex Gundyr,0x5A03,5,4001952,,
        ///Firelink Shrine,0x5A03,7,4001950,,
        ///Untended Graves,0x5A03,4,4001953,,
        ///Champion Gundyr,0x5A03,3,4001954,,
        ///High Wall of Lothric,0xF02,6,3001950,,
        ///Tower on the Wall,0xF03,2,3001955,,,
        ///Vordt of the Boreal Valley,0xF03,5,3001952,,
        ///Vordt (Fog Gate),,,3001955,27.61|-25.49|51.48,-0.01
        ///Dancer of the Boreal Valley,0xF03,3,3001954,,
        ///Dancer (Fog Gate),,,3001955,27.54|-8.58|126.75,3.14
        ///Oceiros the Consumed King,0xF03,6,3001951
        ///Oceiros (Fog Ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarpEntries {
            get {
                return ResourceManager.GetString("WarpEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 0f 28 3d 00 00 00    movaps xmm15,XMMWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///00
        ///44 0f 11 b8 40 0a 00    movups XMMWORD PTR [rax+0xa40],xmm15
        ///00
        ///45 0f 57 ff             xorps  xmm15,xmm15
        ///e9 00 00 00 00          jmp    19 &lt;_main+0x19&gt;.
        /// </summary>
        internal static string WarpHookCode {
            get {
                return ResourceManager.GetString("WarpHookCode", resourceCulture);
            }
        }
    }
}
